# Generated by Django 4.1.2 on 2022-10-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cleaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='cleaning',
            field=models.CharField(choices=[('W', 'Winter'), ('S', 'Spring'), ('M', 'Summer'), ('F', 'Fall')], default='W', max_length=1),
        ),
    ]
