# Generated by Django 4.1.2 on 2022-10-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_cleaning_cleaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('setting', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cleaning',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='cleaning',
            field=models.CharField(choices=[('W', 'Wet Cloth'), ('D', 'Dry Cloth'), ('M', 'MicroFiber'), ('F', 'Feather duster')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='date',
            field=models.DateField(verbose_name='cleaning date'),
        ),
        migrations.AddField(
            model_name='gem',
            name='jewelry',
            field=models.ManyToManyField(to='main_app.jewelry'),
        ),
    ]
